### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by RRREEEEEEEE**
It's important to keep standards even when you're hacking someones site!
Please accept this commit!

### CODE REVIEW

**Comment by mathiasblc** [comment]
You here for the fame, we see you. 👀

**Comment by diamondburned** [comment]
Sorry, this code has to be linted in order to be truly standardized. Please run it through the linters.

**Comment by AlexanderBalson** [comment]
@RRREEEEEEEE you have a great username.

Also >accepted
This is hilarious

**Comment by RRREEEEEEEE** [comment]
Thanks for all the hard work guys! Looking forward to next release!

**Pull request merged**
